signonotron2/config/routes.rb
Signonotron2::Application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    invitations: 'invitations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_scope :user do
    post "/users/invitation/resend/:id" => "invitations#resend", :as => "resend_user_invitation"
    put "/users/confirmation" => "confirmations#update"
    resource :two_step_verification, only: [:show, :update],
      path: "/users/two_step_verification",
      controller: "devise/two_step_verification" do
      resource :session, only: [:new, :create], controller: "devise/two_step_verification_session"

      member { get :prompt }
    end
  end

  resources :users, except: [:show] do
    member do
      get :edit_email_or_passphrase
      patch :update_email
      patch :update_passphrase
      post :unlock
      put :resend_email_change
      delete :cancel_email_change
      get :event_logs
      patch :reset_two_step_verification
    end
  end
  resource :user, only: [:show]

  resources :batch_invitations, only: [:new, :create, :show]
  resources :organisations, only: [:index]
  resources :suspensions, only: [:edit, :update]

  resources :doorkeeper_applications, only: [:index, :edit, :update] do
    member do
      get :users_with_access
    end
    resources :supported_permissions, only: [:index, :new, :create, :edit, :update]
  end

  resources :api_users, only: [:new, :create, :index, :edit, :update] do
    resources :authorisations, only: [:new, :create] do
      member do
        # revoke is a GET request so that we don't have to use
        # `link_to 'Revoke' ... method: :delete`, which works
        # only with javascript
        get :revoke
      end
    end
  end

  # Gracefully handle GET on page (e.g. hit refresh) reached by a render to a POST
  match "/users/:id" => redirect("/users/%{id}/edit"), via: :get
  match "/suspensions/:id" => redirect("/users/%{id}/edit"), via: :get

  # compatibility with Sign-on-o-tron 1
  post "oauth/access_token" => "doorkeeper/tokens#create"

  # Prototyping
  get '/phone-unavailable' => 'prototype#phone_unavailable'
  get '/recover-account'   => 'prototype#recover_account'

  root to: 'root#index'
end

signonotron2/app/controllers/doorkeeper_applications_controller.rb
class DoorkeeperApplicationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_and_authorize_application, except: :index

  respond_to :html

  def index
    authorize Doorkeeper::Application
    @applications = Doorkeeper::Application.all
  end

  def update
    if @application.update_attributes(doorkeeper_application_params)
      redirect_to doorkeeper_applications_path, notice: "Successfully updated #{@application.name}"
    else
      respond_with @application
    end
  end

  def users_with_access
    query = policy_scope(User).with_access_to_application(@application)
    @users = query.page(params[:page]).per(100)
  end

  private

  def load_and_authorize_application
    @application = Doorkeeper::Application.find(params[:id])
    authorize @application
  end

  def doorkeeper_application_params
    # Since our Pundit policies ensure that only a superadmin can access this
    # controller, we can whitelist all attributes the edit form can modify
    params.require(:doorkeeper_application).permit(
      :name,
      :description,
      :uid,
      :secret,
      :redirect_uri,
      :home_uri,
      :supports_push_updates,
    )
  end
end

signonotron2/app/views/doorkeeper_applications/edit.html.erb
<% content_for :title, "Edit application" %>

<ol class="breadcrumb">
  <li><%= link_to 'Applications', doorkeeper_applications_path %></li>
  <li class="active"><%= @application.name %></li>
</ol>

<div class="page-title">
  <h1>Edit application &ldquo;<%= @application.name %>&rdquo;</h1>
</div>

<p>
  <%= link_to "Users with access", users_with_access_doorkeeper_application_path(@application) %>
</p>

<%= form_for @application, :html => {:class => 'well'} do |f| %>

  <% if @application.errors.count > 0 %>
    <div class="alert alert-danger remove-bottom-margin">
      <ul>
        <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, required: "required", class: 'form-control input-md-6' %>
    <span class="help-block">Shown on the Signon homepage.</span>
  </p>

  <p class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, required: "required", class: 'form-control input-md-6' %>
    <span class="help-block">Shown on the Signon homepage.</span>
  </p>

  <p class="form-group">
    <%= f.label :home_uri, "Home URI" %>
    <%= f.text_field :home_uri, required: "required", class: 'form-control input-md-6' %>
    <span class="help-block">Used to link to the app on the Signon homepage.</span>
  </p>

  <p class="form-group">
    <%= f.label :redirect_uri, "Redirect URI" %>
    <%= f.text_field :redirect_uri, required: "required", class: 'form-control input-md-6' %>
    <span class="help-block">The app should expect this URI. Used in the signin redirect dance.</span>
  </p>

  <p class="form-group">
    <%= f.label :uid, "UID" %>
    <%= f.text_field :uid, required: "required", class: 'form-control input-md-6' %>
    <span class="help-block">The app has a copy of this. Used in the signin redirect dance.</span>
  </p>

  <p class="form-group">
    <%= f.label :secret %>
    <%= f.text_field :secret, required: "required", class: 'form-control input-md-6' %>
    <span class="help-block">The app has a copy of this. Used in the signin redirect dance.</span>
  </p>

  <p class="checkbox">
    <label>
      <%= f.check_box :supports_push_updates %> Send push updates to this app
    </label>
  </p>

  <% if policy(Doorkeeper::Application).edit? %>
    <hr />
    <p class="add-top-margin">
      <%= link_to "Edit supported permissions", doorkeeper_application_supported_permissions_path(@application) %>
    </p>
    <hr />
  <% end %>

  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

signonotron2/app/views/doorkeeper_applications/index.html.erb
<% content_for :title, "Single Signon applications" %>
<div class="page-title">
  <h1>Single Signon Applications</h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr class="table-header">
      <th scope="col">Name</th>
      <th scope="col">Redirect URI</th>
      <th scope="col">Home URI</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td>
          <%= link_to application.name, edit_doorkeeper_application_path(application) %>
          <br>
          <%= application.description %>
        </td>
        <td><%= application.redirect_uri %></td>
        <td><%= link_to application.home_uri, application.home_uri %></td>
        <td><%= link_to "Edit", edit_doorkeeper_application_path(application) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

signonotron2/app/views/doorkeeper_applications/users_with_access.html.erb
<% content_for :title, "Users with access to #{@application.name}" %>

<ol class="breadcrumb">
  <li><%= link_to 'Applications', doorkeeper_applications_path %></li>
  <li><%= link_to @application.name, edit_doorkeeper_application_path(@application) %></li>
  <li class="active">Users with access</li>
</ol>

<div class="page-title">
  <h1>Users with access to <%= @application.name %></h1>
</div>

<%= paginate @users, theme: 'twitter-bootstrap-3' %>

<table class="table table-striped table-bordered">
  <thead>
    <tr class="table-header">
      <th scope="col">Name and email</th>
      <th scope="col">Role</th>
      <th scope="col">Organisation</th>
      <th scope="col">Sign-in count</th>
      <th scope="col">Last sign-in</th>
      <th scope="col">Status</th>
      <th scope="col">Permissions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="email">
          <%= user.suspended? ? "<del>".html_safe : "" %>
            <strong>
              <%= link_to "#{user.name}", edit_user_path(user) %>
            </strong>
          <%= user.suspended? ? "</del>".html_safe : "" %>
          <br><span class="text-muted"><%= user.email %></span>
        </td>
        <td class="role"><%= user.role.humanize %></td>
        <td class="organisation"><%= user.organisation.try(:name) %></td>
        <td><%= user.sign_in_count %></td>
        <td class="last-sign-in">
          <% if user.current_sign_in_at %>
            <%= time_ago_in_words(user.current_sign_in_at) %> ago
          <% else %>
            never signed in
          <% end %>
        </td>
        <td><%= user.status.humanize %></td>
        <td><%= user.eager_loaded_permission_for(@application).to_sentence %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users, theme: 'twitter-bootstrap-3' %>