signonotron2/config/routes.rb
Signonotron2::Application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    invitations: 'invitations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_scope :user do
    post "/users/invitation/resend/:id" => "invitations#resend", :as => "resend_user_invitation"
    put "/users/confirmation" => "confirmations#update"
    resource :two_step_verification, only: [:show, :update],
      path: "/users/two_step_verification",
      controller: "devise/two_step_verification" do
      resource :session, only: [:new, :create], controller: "devise/two_step_verification_session"

      member { get :prompt }
    end
  end

  resources :users, except: [:show] do
    member do
      get :edit_email_or_passphrase
      patch :update_email
      patch :update_passphrase
      post :unlock
      put :resend_email_change
      delete :cancel_email_change
      get :event_logs
      patch :reset_two_step_verification
    end
  end
  resource :user, only: [:show]

  resources :batch_invitations, only: [:new, :create, :show]
  resources :organisations, only: [:index]
  resources :suspensions, only: [:edit, :update]

  resources :doorkeeper_applications, only: [:index, :edit, :update] do
    member do
      get :users_with_access
    end
    resources :supported_permissions, only: [:index, :new, :create, :edit, :update]
  end

  resources :api_users, only: [:new, :create, :index, :edit, :update] do
    resources :authorisations, only: [:new, :create] do
      member do
        # revoke is a GET request so that we don't have to use
        # `link_to 'Revoke' ... method: :delete`, which works
        # only with javascript
        get :revoke
      end
    end
  end

  # Gracefully handle GET on page (e.g. hit refresh) reached by a render to a POST
  match "/users/:id" => redirect("/users/%{id}/edit"), via: :get
  match "/suspensions/:id" => redirect("/users/%{id}/edit"), via: :get

  # compatibility with Sign-on-o-tron 1
  post "oauth/access_token" => "doorkeeper/tokens#create"

  # Prototyping
  get '/phone-unavailable' => 'prototype#phone_unavailable'
  get '/recover-account'   => 'prototype#recover_account'

  root to: 'root#index'
end

signonotron2/app/models/supported_permission.rb
class SupportedPermission < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :application, class_name: 'Doorkeeper::Application'
  has_many :user_application_permissions, dependent: :destroy, inverse_of: :supported_permission

  validates_presence_of :name
  validate :signin_permission_name_not_changed

  default_scope { order(:name) }
  scope :delegatable, -> { where(delegatable: true) }
  scope :grantable_from_ui, -> { where(grantable_from_ui: true) }

private

  def signin_permission_name_not_changed
    return if new_record? || !name_changed?

    if name_change.first.downcase == 'signin'
      errors.add(:name, "of permission #{name_change.first} can't be changed")
    end
  end
end

signonotron2/app/controllers/supported_permissions_controller.rb
class SupportedPermissionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_and_authorize_application
  respond_to :html

  def new
    @supported_permission = @application.supported_permissions.build
  end

  def edit
    @supported_permission = supported_permission
  end

  def create
    @supported_permission = @application.supported_permissions.build(supported_permission_parameters)
    if @supported_permission.save
      redirect_to doorkeeper_application_supported_permissions_path,
        notice: "Successfully added permission #{@supported_permission.name} to #{@application.name}"
    else
      render :new
    end
  end

  def update
    @supported_permission = supported_permission
    if @supported_permission.update_attributes(supported_permission_parameters)
      redirect_to doorkeeper_application_supported_permissions_path,
        notice: "Successfully updated permission #{@supported_permission.name}"
    else
      render :edit
    end
  end

private

  def load_and_authorize_application
    @application = Doorkeeper::Application.find(params[:doorkeeper_application_id])
    authorize @application, :manage_supported_permissions?
  end

  def supported_permission_parameters
    params.require(:supported_permission).permit(:name, :delegatable)
  end

  def supported_permission
    SupportedPermission.find(params[:id])
  end
end

signonotron2/app/views/supported_permissions/_form.html.erb
<%- unless @supported_permission.errors.empty? -%>
  <div class="alert alert-danger add-top-margin">
    <ul class="errors">
      <%- @supported_permission.errors.full_messages.each do |msg| -%>
      <li><%= msg %></li>
      <%- end -%>
    </ul>
  </div>
<%- end -%>

<div class="well">
  <%= form_for [@application, @supported_permission] do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Permission name' %>
        <% if f.object.name.try(:downcase) == 'signin' %>
          <%= f.object.name %>
        <% else %>
          <%= f.text_field :name, placeholder: t('supported_permissions.form.placeholder.name'), class: 'form-control input-md-4', autofocus: 'autofocus' %>
        <% end %>
    </div>
    <hr />
    <p class="checkbox">
      <label>
        <%= f.check_box :delegatable %> <%= t('supported_permissions.form.delegatable') %>
      </label>
    </p>
    <hr />
    <%= f.submit "Save permission", class: "btn btn-success" %>
  <% end %>
</div>

signonotron2/app/views/supported_permissions/edit.html.erb
<% content_for :title, "Edit permission" %>

<ol class="breadcrumb">
  <li><%= link_to 'Applications', doorkeeper_applications_path %></li>
  <li><%= link_to @application.name, edit_doorkeeper_application_path(@application) %></li>
  <li><%= link_to 'Permissions', doorkeeper_application_supported_permissions_path(@application) %></li>
  <li class="active">Edit permission</li>
</ol>

<div class="page-title">
  <h1>Edit permission “<%= @supported_permission.name %>”</h1>
</div>

<%= render 'form' %>

signonotron2/app/views/supported_permissions/index.html.erb
<% content_for :title, "Permissions for #{@application.name}" %>

<ol class="breadcrumb">
  <li><%= link_to 'Applications', doorkeeper_applications_path %></li>
  <li><%= link_to @application.name, edit_doorkeeper_application_path(@application) %></li>
  <li class="active">Permissions</li>
</ol>

<div class="page-title">
  <h1>Permissions for “<%= @application.name %>”</h1>
</div>

<%= link_to new_doorkeeper_application_supported_permission_path, id: "add", class: "btn btn-success" do %>
  <span class="glyphicon glyphicon-plus"></span> Add permission
<% end %>

<table class="table table-striped table-bordered add-top-margin">
  <thead>
    <tr class="table-header">
      <th>
        Permission name
      </th>
      <th>
        Created
      </th>
      <th>
        Can be delegated?
      </th>
      <th>
        Actions
      </th>
    </tr>
  </thead>
  <tbody>
    <% @application.sorted_supported_permissions_grantable_from_ui.each do |supported_permission| %>
      <tr>
        <td class="name">
          <%= link_to supported_permission.name, edit_doorkeeper_application_supported_permission_path(@application, supported_permission) %>
        </td>
        <td>
          <%= supported_permission.created_at.to_date.to_s(:govuk_date) %>
        </td>
        <td class="delegatable">
          <%= supported_permission.delegatable? ? 'Yes' : 'No' %>
        </td>
        <td>
          <%= link_to 'Edit', edit_doorkeeper_application_supported_permission_path(@application, supported_permission) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

signonotron2/app/views/supported_permissions/new.html.erb
<% content_for :title, "Single Signon application permissions" %>

<ol class="breadcrumb">
  <li><%= link_to 'Applications', doorkeeper_applications_path %></li>
  <li><%= link_to @application.name, edit_doorkeeper_application_path(@application) %></li>
  <li><%= link_to 'Permissions', doorkeeper_application_supported_permissions_path(@application) %></li>
  <li class="active">Add permission</li>
</ol>

<div class="page-title">
  <h1>Add permission</h1>
</div>

<%= render 'form' %>