signonotron2/config/routes.rb
Signonotron2::Application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    invitations: 'invitations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_scope :user do
    post "/users/invitation/resend/:id" => "invitations#resend", :as => "resend_user_invitation"
    put "/users/confirmation" => "confirmations#update"
    resource :two_step_verification, only: [:show, :update],
      path: "/users/two_step_verification",
      controller: "devise/two_step_verification" do
      resource :session, only: [:new, :create], controller: "devise/two_step_verification_session"

      member { get :prompt }
    end
  end

  resources :users, except: [:show] do
    member do
      get :edit_email_or_passphrase
      patch :update_email
      patch :update_passphrase
      post :unlock
      put :resend_email_change
      delete :cancel_email_change
      get :event_logs
      patch :reset_two_step_verification
    end
  end
  resource :user, only: [:show]

  resources :batch_invitations, only: [:new, :create, :show]
  resources :organisations, only: [:index]
  resources :suspensions, only: [:edit, :update]

  resources :doorkeeper_applications, only: [:index, :edit, :update] do
    member do
      get :users_with_access
    end
    resources :supported_permissions, only: [:index, :new, :create, :edit, :update]
  end

  resources :api_users, only: [:new, :create, :index, :edit, :update] do
    resources :authorisations, only: [:new, :create] do
      member do
        # revoke is a GET request so that we don't have to use
        # `link_to 'Revoke' ... method: :delete`, which works
        # only with javascript
        get :revoke
      end
    end
  end

  # Gracefully handle GET on page (e.g. hit refresh) reached by a render to a POST
  match "/users/:id" => redirect("/users/%{id}/edit"), via: :get
  match "/suspensions/:id" => redirect("/users/%{id}/edit"), via: :get

  # compatibility with Sign-on-o-tron 1
  post "oauth/access_token" => "doorkeeper/tokens#create"

  # Prototyping
  get '/phone-unavailable' => 'prototype#phone_unavailable'
  get '/recover-account'   => 'prototype#recover_account'

  root to: 'root#index'
end

signonotron2/app/models/api_user.rb
class ApiUser < User
  default_scope { where(api_user: true).order(:name) }

  DEFAULT_TOKEN_LIFE = 10.years.to_i
end

signonotron2/app/controllers/api_users_controller.rb
class ApiUsersController < ApplicationController
  include UserPermissionsControllerMethods

  before_filter :authenticate_user!
  before_filter :load_and_authorize_api_user, only: [:edit, :update]
  helper_method :applications_and_permissions, :visible_applications

  respond_to :html

  def index
    authorize ApiUser
    @api_users = ApiUser.includes(application_permissions: :application)
  end

  def new
    authorize ApiUser
    @api_user = ApiUser.new
  end

  def create
    authorize ApiUser

    password = SecureRandom.urlsafe_base64
    @api_user = ApiUser.new(api_user_params.merge(password: password, password_confirmation: password))
    @api_user.skip_confirmation!
    @api_user.api_user = true

    if @api_user.save
      EventLog.record_event(@api_user, EventLog::API_USER_CREATED, initiator: current_user)
      redirect_to [:edit, @api_user], notice: "Successfully created API user"
    else
      render :new
    end
  end

  def update
    @api_user.skip_reconfirmation!
    if @api_user.update_attributes(api_user_params)
      @api_user.application_permissions.reload
      PermissionUpdater.perform_on(@api_user)

      redirect_to :api_users, notice: "Updated API user #{@api_user.email} successfully"
    else
      render :edit
    end
  end

private

  def load_and_authorize_api_user
    @api_user = ApiUser.find(params[:id])
    authorize @api_user
  end

  def api_user_params
    UserParameterSanitiser.new(
      user_params: params.require(:api_user),
      current_user_role: current_user.role.to_sym,
    ).sanitise
  end
end

signonotron2/app/helpers/api_users_helper.rb
module ApiUsersHelper
  def truncate_access_token(token)
    raw "#{token[0..7]}#{'&bull;' * 24}#{token[-8..-1]}"
  end
end

signonotron2/app/views/api_users/_form_fields.html.erb
<% if @api_user.errors.present? %>
  <div class="alert alert-danger">
    <ul>
      <% @api_user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: 'form-control input-md-6', required: true %>
</p>

<p class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control input-md-6', required: true %>
</p>

<% unless f.object.new_record? %>
  <h2 class="add-vertical-margins">Tokens</h2>

  <% if authorisation = flash[:authorisation] %>
    <div class="alert alert-danger">
      Make sure to copy the access token for <%= authorisation[:application_name] %> now. You won't be able to see it again!
    </div>
    <div class="alert alert-info">
      Access token for <%= authorisation[:application_name] %>: <span id='access-token'><%= authorisation[:token] %></span>
      <%= link_to 'Copy to clipboard', '#', class: 'btn btn-info add-left-margin', data: { 'clipboard-target' => 'access-token' }, id: 'clip-button', title: 'Click to copy access token' %>
    </div>
  <% end %>
  <table class="table table-bordered table-on-white">
    <thead>
      <tr class="table-header">
        <th>Application</th>
        <th>Token (hidden)</th>
        <th>Generated</th>
        <th>Expires</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @api_user.authorisations.where(revoked_at: nil).each do |authorisation| %>
        <tr>
          <td><%= authorisation.application.name %></td>
          <td><code><%= truncate_access_token(authorisation.token) %></code></td>
          <td>
            <%= Time.at(authorisation.created_at).to_date.to_s(:govuk_date) %>
          </td>
          <td>
            <%= Time.at(authorisation.created_at.to_f + authorisation.expires_in).to_date.to_s(:govuk_date) %>
          </td>
          <td>
            <div class="btn-group">
              <%= link_to "Re-generate", revoke_api_user_authorisation_path(@api_user.id, authorisation.id, regenerate: true), class: "btn btn-default" %>
              <%= link_to "Revoke", revoke_api_user_authorisation_path(@api_user.id, authorisation.id), class: "btn btn-default" %>
            </div>
          </td>
      <% end %>
    </tbody>
  </table>
  <p>
    <%= link_to [:new, @api_user, :authorisation], class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-plus glyphicon-smaller-than-text"></span> Add application token
    <% end %>
  </p>

  <% if @api_user.authorisations.present? %>
    <hr />
    <h2 class="add-vertical-margins">Permissions</h2>
    <%= render partial: "shared/user_permissions", locals: { user_object: f.object }%>
  <% end %>

<% end %>

<script>
  $(document).ready(function() {
    new ZeroClipboard($("#clip-button"));
  });
</script>

signonotron2/app/views/api_users/edit.html.erb
<% content_for :title, "Edit [#{@api_user.name}]" %>

<h1>Edit API User &ldquo;<%= @api_user.name %>&rdquo;</h1>

<p class="suspenders">
  User <strong><%= @api_user.status %></strong> &bull;
  <%= link_to "Account access log", event_logs_user_path(@api_user) %> &bull;
  <%= link_to "#{@api_user.suspended? ? "Uns" : "S"}uspend user", edit_suspension_path(@api_user) %>
</p>

<% if @api_user.suspended? and @api_user.reason_for_suspension.present? %>
  <p class="alert alert-warning">
    <strong>User suspended:</strong> <em><%= @api_user.reason_for_suspension %></em>
  </p>
<% end %>

<%= form_for @api_user, :html => {:class => 'well add-top-margin'} do |f| %>
  <%= render partial: "form_fields", locals: { f: f } %>

  <hr>

  <%= f.submit 'Update API user', :class => 'btn btn-primary' %>
<% end %>

signonotron2/app/views/api_users/index.html.erb
<% content_for :title, "API Users" %>

<div class="row">
  <div class="col-md-5 page-title remove-top-margin">
    <h1>API Users</h1>
  </div>

  <div class="col-md-7 text-right">
    <%= link_to "Create API user", new_api_user_path, class: "btn btn-success add-top-margin" %>
  </div>
</div>

  <table class="table table-striped table-bordered" data-module="filterable-table">
    <thead>
      <tr class="table-header">
        <th scope="col" style="width: 300px">Name and email</th>
        <th scope="col">Apps</th>
        <th scope="col">Role</th>
        <th scope="col" style="width: 75px">Sign-ins</th>
        <th scope="col">Created</th>
        <th scope="col">Suspended?</th>
      </tr>
      <tr class="if-no-js-hide table-header-secondary">
        <td colspan="6">
          <form>
            <label for="api-filter" class="rm">Filter API users</label>
            <input id="api-filter" type="text" class="form-control normal js-filter-table-input" placeholder="Filter API users">
          </form>
        </td>
      </tr>
    </thead>
    <tbody>
      <% @api_users.each do |user| %>
        <tr>
          <td class="email">
            <%= user.suspended? ? "<del>".html_safe : "" %>
              <%= link_to "#{user.name}", edit_api_user_path(user), class: 'bold js-open-on-submit' %>
            <%= user.suspended? ? "</del>".html_safe : "" %>
            <span class="text-muted"><br /><%= user.email %></span>
          </td>
          <td>
            <% visible_applications(user).each do |application| %>
              <% if permissions_for_application = user.permissions_for(application) %>
                <abbr title="Permissions: <%= permissions_for_application.to_sentence %>" data-toggle="tooltip" data-placement="right"><%= application.name %></abbr><br />
              <% end %>
            <% end %>
          </td>
          <td class="role"><%= user.role.humanize %></td>
          <td><%= user.sign_in_count %></td>
          <td><%= time_ago_in_words(user.created_at) %> ago</td>
          <td><%= user.suspended? ? "Yes" : "No" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

signonotron2/app/views/api_users/new.html.erb
<% content_for :title, "Create new API user" %>

<h1>Create new API user</h1>

<%= form_for @api_user, html: { class: 'well add-top-margin' } do |f| %>
  <%= render partial: "form_fields", locals: { f: f } %>

  <%= f.submit "Create API user", :class => 'btn btn-success add-top-margin' %>
<% end %>