signonotron2/config/routes.rb
Signonotron2::Application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    invitations: 'invitations',
    sessions: 'sessions',
    passwords: 'passwords',
    confirmations: 'confirmations'
  }

  devise_scope :user do
    post "/users/invitation/resend/:id" => "invitations#resend", :as => "resend_user_invitation"
    put "/users/confirmation" => "confirmations#update"
    resource :two_step_verification, only: [:show, :update],
      path: "/users/two_step_verification",
      controller: "devise/two_step_verification" do
      resource :session, only: [:new, :create], controller: "devise/two_step_verification_session"

      member { get :prompt }
    end
  end

  resources :users, except: [:show] do
    member do
      get :edit_email_or_passphrase
      patch :update_email
      patch :update_passphrase
      post :unlock
      put :resend_email_change
      delete :cancel_email_change
      get :event_logs
      patch :reset_two_step_verification
    end
  end
  resource :user, only: [:show]

  resources :batch_invitations, only: [:new, :create, :show]
  resources :organisations, only: [:index]
  resources :suspensions, only: [:edit, :update]

  resources :doorkeeper_applications, only: [:index, :edit, :update] do
    member do
      get :users_with_access
    end
    resources :supported_permissions, only: [:index, :new, :create, :edit, :update]
  end

  resources :api_users, only: [:new, :create, :index, :edit, :update] do
    resources :authorisations, only: [:new, :create] do
      member do
        # revoke is a GET request so that we don't have to use
        # `link_to 'Revoke' ... method: :delete`, which works
        # only with javascript
        get :revoke
      end
    end
  end

  # Gracefully handle GET on page (e.g. hit refresh) reached by a render to a POST
  match "/users/:id" => redirect("/users/%{id}/edit"), via: :get
  match "/suspensions/:id" => redirect("/users/%{id}/edit"), via: :get

  # compatibility with Sign-on-o-tron 1
  post "oauth/access_token" => "doorkeeper/tokens#create"

  # Prototyping
  get '/phone-unavailable' => 'prototype#phone_unavailable'
  get '/recover-account'   => 'prototype#recover_account'

  root to: 'root#index'
end

signonotron2/app/controllers/users_controller.rb
require 'csv'

class UsersController < ApplicationController
  include UserPermissionsControllerMethods

  before_filter :authenticate_user!, except: :show
  before_filter :load_and_authorize_user, except: [:index, :show]
  helper_method :applications_and_permissions, :any_filter?
  respond_to :html

  before_filter :doorkeeper_authorize!, only: :show
  before_filter :validate_token_matches_client_id, only: :show
  skip_after_filter :verify_authorized, only: :show

  def show
    current_resource_owner.permissions_synced!(application_making_request)
    respond_to do |format|
      format.json do
        presenter = UserOAuthPresenter.new(current_resource_owner, application_making_request)
        render json: presenter.as_hash.to_json
      end
    end
  end

  def index
    authorize User

    @users = policy_scope(User).includes(:organisation)
    filter_users if any_filter?
    respond_to do |format|
      format.html do
        paginate_users
      end
      format.csv do
        headers['Content-Disposition'] = 'attachment; filename="signon_users.csv"'
        render text: export, content_type: 'text/csv'
      end
    end
  end

  def update
    raise Pundit::NotAuthorizedError if current_user.organisation_admin? &&
        ! current_user.organisation.subtree.map(&:id).include?(params[:user][:organisation_id].to_i)

    @user.skip_reconfirmation!
    if @user.update_attributes(user_params)
      send_two_step_flag_notification(@user)

      @user.application_permissions.reload
      PermissionUpdater.perform_on(@user)

      if email_change = @user.previous_changes[:email]
        EventLog.record_email_change(@user, email_change.first, email_change.last, current_user)
        @user.invite! if @user.invited_but_not_yet_accepted?
        email_change.each do |to_address|
          UserMailer.email_changed_by_admin_notification(@user, email_change.first, to_address).deliver_later
        end
      end

      redirect_to users_path, notice: "Updated user #{@user.email} successfully"
    else
      render :edit
    end
  end

  def unlock
    EventLog.record_event(@user, EventLog::MANUAL_ACCOUNT_UNLOCK, initiator: current_user)
    @user.unlock_access!
    flash[:notice] = "Unlocked #{@user.email}"
    redirect_to :back
  end

  def resend_email_change
    @user.resend_confirmation_instructions
    if @user.errors.empty?
      notice = if @user.normal?
                 "An email has been sent to #{@user.unconfirmed_email}. Follow the link in the email to update your address."
               else
                 "Successfully resent email change email to #{@user.unconfirmed_email}"
               end
      redirect_to root_path, notice: notice
    else
      redirect_to edit_user_path(@user), alert: "Failed to send email change email"
    end
  end

  def cancel_email_change
    @user.unconfirmed_email = nil
    @user.confirmation_token = nil
    @user.save(validate: false)
    redirect_to :back
  end

  def event_logs
    authorize @user
    @logs = @user.event_logs.page(params[:page]).per(100) if @user
  end

  def update_email
    current_email = @user.email
    new_email = params[:user][:email]
    if current_email == new_email.strip
      flash[:alert] = "Nothing to update."
      render :edit_email_or_passphrase
    elsif @user.update_attributes(email: new_email)
      EventLog.record_email_change(@user, current_email, new_email)
      UserMailer.email_changed_notification(@user).deliver_later
      redirect_to root_path, notice: "An email has been sent to #{new_email}. Follow the link in the email to update your address."
    else
      flash[:alert] = "Failed to change email."
      render :edit_email_or_passphrase
    end
  end

  def update_passphrase
    if @user.update_with_password(password_params)
      EventLog.record_event(@user, EventLog::SUCCESSFUL_PASSPHRASE_CHANGE)
      flash[:notice] = t(:updated, scope: 'devise.passwords')
      sign_in(@user, bypass: true)
      redirect_to root_path
    else
      EventLog.record_event(@user, EventLog::UNSUCCESSFUL_PASSPHRASE_CHANGE)
      render :edit_email_or_passphrase
    end
  end

  def reset_two_step_verification
    @user.reset_2sv!(current_user)
    UserMailer.two_step_reset(@user).deliver_later

    redirect_to :root, notice: "Reset 2-step verification for #{@user.email}"
  end

  private

  def load_and_authorize_user
    @user = current_user.normal? ? current_user : User.find(params[:id])
    authorize @user
  end

  def filter_users
    @users = @users.filter(params[:filter]) if params[:filter].present?
    @users = @users.with_role(params[:role]) if can_filter_role?
    @users = @users.with_organisation(params[:organisation]) if params[:organisation].present?
    @users = @users.with_status(params[:status]) if params[:status].present?
    @users = @users.with_2sv_enabled(params[:two_step_status]) if params[:two_step_status].present?
  end

  def can_filter_role?
    params[:role].present? &&
      current_user.manageable_roles.include?(params[:role])
  end

  def should_include_permissions?
    params[:format] == 'csv'
  end

  def paginate_users
    if any_filter?
      if @users.is_a?(Array)
        @users = Kaminari.paginate_array(@users).page(params[:page]).per(100)
      else
        @users = @users.page(params[:page]).per(100)
      end
    else
      @users, @sorting_params = @users.alpha_paginate(params[:letter], ALPHABETICAL_PAGINATE_CONFIG)
    end
  end

  def any_filter?
    params[:filter].present? ||
      params[:role].present? ||
      params[:status].present? ||
      params[:organisation].present? ||
      params[:two_step_status].present?
  end

  def application_making_request
    ::Doorkeeper::Application.find(doorkeeper_token.application_id)
  end

  def validate_token_matches_client_id
    # FIXME: Once gds-sso is updated everywhere, this should always validate
    # the client_id param.  It should 401 if no client_id is given.
    if params[:client_id].present?
      if params[:client_id] != doorkeeper_token.application.uid
        head :unauthorized
      end
    end
  end

  def export
    applications = Doorkeeper::Application.all
    CSV.generate do |csv|
      presenter = UserExportPresenter.new(applications)
      csv << presenter.header_row
      @users.includes(:organisation).find_each do |user|
        csv << presenter.row(user)
      end
    end
  end

  def send_two_step_flag_notification(user)
    if user.send_two_step_flag_notification?
      UserMailer.two_step_flagged(user).deliver_later
    end
  end

  def user_params
    UserParameterSanitiser.new(
      user_params: params.require(:user),
      current_user_role: current_user.role.to_sym,
    ).sanitise
  end

  def password_params
    params.require(:user).permit(
      :current_password,
      :password,
      :password_confirmation,
    )
  end
end

signonotron2/app/helpers/users_helper.rb
module UsersHelper
  def two_step_status(user)
    user.has_2sv? ? 'Enabled' : 'Not set up'
  end

  def organisation_options(form_builder)
    accessible_organisations = policy_scope(Organisation)
    options_from_collection_for_select(accessible_organisations, :id,
      :name_with_abbreviation, selected: form_builder.object.organisation_id)
  end

  def organisation_select_options
    { include_blank: is_org_admin? ? false : 'None' }
  end

  def user_email_tokens(user = current_user)
    [user.email] + DeviseZxcvbn::EmailTokeniser.split(user.email)
  end

  def minimum_password_length
    User.password_length.min
  end

  def edit_user_path_by_user_type(user)
    user.api_user? ? edit_api_user_path(user) : edit_user_path(user)
  end

  def is_org_admin?
    current_user.role == 'organisation_admin'
  end

  def sync_needed?(permissions)
    max_updated_at = permissions.map(&:updated_at).compact.max
    max_last_synced_at = permissions.map(&:last_synced_at).compact.max
    max_updated_at.present? && max_last_synced_at.present? ? max_updated_at > max_last_synced_at : false
  end
end

signonotron2/app/views/users/_form_errors.html.erb
<% if @user.errors.count > 0 %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <%= content_tag :li, message, data: track_analytics_data(:danger, message) %>
      <% end %>
    </ul>
  </div>
<% end %>

signonotron2/app/views/users/_form_fields.html.erb
<p class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: 'form-control input-md-6 ' %>
</p>

<p class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control input-md-6 add-label-margin' %>
  <% if f.object.persisted? %>
    <% if f.object.invited_but_not_yet_accepted? %>
      <span class="help-block">Changes will trigger a new signup email.</span>
    <% end %>
  <% end %>
</p>

<% if f.object.unconfirmed_email.present? %>
  <p class="form-group">
    <%= f.label :unconfirmed_email, "Pending email" %>
    <%= f.text_field :unconfirmed_email, readonly: "readonly", disabled: "disabled", class: 'form-control' %>

    <div class="help-block add-bottom-margin">
      <%= link_to "Resend email change", resend_email_change_user_path(f.object), :method => :put, :class => "btn btn-primary add-right-margin" %>
      <%= link_to "Cancel email change", cancel_email_change_user_path(f.object), :method => :delete, :class => "btn btn-danger" %>
    </div>
  </p>
<% end %>

<% if policy(User).assign_role? %>
  <p class="form-group">
    <%= f.label :role %><br />
    <%= f.select :role, options_for_select(filtered_user_roles.map(&:humanize).zip(filtered_user_roles), f.object.role), {}, class: "chosen-select form-control", 'data-module' => 'chosen' %>
    <span class="help-block">
      <strong>Admins</strong> can create and edit normal users.<br />
      <strong>Superadmins</strong> can create and edit all user types and edit applications.
    </span>
  </p>
<% end %>

<% if policy(User).flag_2sv? %>
  <dl>
    <dt>Account security</dt>
    <dd>
      <% if f.object.has_2sv? %>
        <p>2-step verification enabled</p>
        <ul>
          <li>
            <%= link_to 'Reset 2-step verification',
              reset_two_step_verification_user_path(@user),
              data: { confirm: 'Are you sure?' },
              method: :patch
              %><br/>
            Allows user to sign in without a verification code.<br/>
            User will be prompted to set up 2-step verification again the next time they sign in.
          </li>
        </ul>
      <% else %>
        <p>2-step verification not set up</p>
        <p class="checkbox">
          <%= f.label :require_2sv do %>
            <%= f.check_box :require_2sv %> Ask user to set up 2-step verification
          <% end %>
        </p>
      <% end %>
    </dd>
  </dl>
<% end %>

<p class="form-group">
  <%= f.label :organisation_id, "Organisation" %><br />
  <%= f.select :organisation_id, organisation_options(f), organisation_select_options, { class: "chosen-select form-control", 'data-module' => 'chosen' } %>
</p>

<h2 class="add-vertical-margins">Permissions</h2>

<%= render partial: "shared/user_permissions", locals: { user_object: f.object }%>

signonotron2/app/views/users/_pagination.html.erb
<% position ||= nil %>
<% if any_filter? %>
  <% if position == 'top' %>
    <h2 class="<%= @users.total_count > 100 ? 'remove' : 'add' %>-bottom-margin"><%= pluralize(number_with_delimiter(@users.total_count), 'user') %></h2>
  <% end %>
  <%= paginate(@users, theme: 'twitter-bootstrap-3') %>
<% else %>
  <h3 class="remove-bottom-margin">Users by initial</h3>
  <%= alphabetical_paginate(@sorting_params) %>
<% end %>

signonotron2/app/views/users/_user_filter.html.erb
<nav class="filters">
  <div class="panel panel-default">
    <header class="panel-heading">
      <% if any_filter? %>
        <%= link_to users_path,
          class: 'remove-filters inherit',
          title: 'Remove all filters' do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      <% end %>
      <ul class="nav nav-compact nav-pills">
        <li class="nav-pill-text">
          <strong>Filter by</strong>
        </li>
        <%= render partial: 'user_filter_group', locals: {filter_type: :role} %>
        <%= render partial: 'user_filter_group', locals: {filter_type: :status} %>
        <% if is_org_admin? %>
          <li class="nav-pill-text text-muted"><%= current_user.organisation.name %></li>
        <% else %>
          <%= render partial: 'user_filter_group', locals: {filter_type: :organisation} %>
        <% end %>
        <%= render partial: 'user_filter_group', locals: {filter_type: :two_step_status} %>
        <li class="filter-by-name">
          <%= form_tag nil, method: "get", class: 'add-left-margin form-inline' do %>
          <%= hidden_field_tag :role, params[:role] if params[:role] %>
          <%= hidden_field_tag :status, params[:status] if params[:status] %>
          <%= hidden_field_tag :organisation, params[:organisation] if params[:organisation] %>
          <%= label_tag 'filter', 'Name or email', class: 'add-right-margin' %>
          <%= text_field_tag "filter", params[:filter], class: 'form-control filter-by-name-field' %>
          <%= submit_tag "Search", class: "btn btn-default" %>
          <% end %>
        </li>
        <li class="<% if any_filter? %>add-right-margin <% end %>pull-right">
          <%= link_to "Export as CSV", params.merge(format: "csv"), class: "btn btn-default" %>
        </li>
      </ul>
    </header>
  </div>
</nav>

<%= render partial: 'user_filter_group_no_js', locals: {filter_type: :role} %>
<%= render partial: 'user_filter_group_no_js', locals: {filter_type: :status} %>
<%= render partial: 'user_filter_group_no_js', locals: {filter_type: :organisation} %>
<%= render partial: 'user_filter_group_no_js', locals: {filter_type: :two_step_status} %>

signonotron2/app/views/users/_user_filter_group.html.erb
<%
  filter_title = title_from(filter_type)
  filter_value = value_from(filter_type)
%>
<li class="add-margin-right <%= "filter-by-#{filter_type.to_s}-menu"%> <% if params[filter_type] %>selected-and-available<% end %>" <% if filter_type == :organisation %>data-module="organisation-filter"<% end %>>
  <% if params[filter_type] %>
    <%= link_to current_path_with_filter(filter_type, nil),
          class: 'filter-option filter-selected',
          title: 'Remove filter' do %>
          <span class="glyphicon glyphicon-remove"></span><span class="rm">Remove</span>
    <% end %>
  <% end %>
  <%= link_to current_path_with_filter(filter_type, ''),
        class: "filter-option #{params[filter_type] ? 'filter-selected' : ''}",
        data: { toggle: 'dropdown' },
        role: 'button' do %>
    <span class="if-no-js-hide"><%= filter_value || filter_title %></span>
    <span class="if-js-hide"><%= filter_title %></span>
    <span class="if-no-js-hide glyphicon glyphicon-chevron-down"></span>
  <% end %>
  <ul class="dropdown-menu <% if filter_type == :organisation %>js-filter-list<% end %>" role="menu">
    <% if filter_type == :organisation %>
      <li class="list-filter">
        <form>
          <label for="organisation-list-filter" class="rm">Search organisations</label>
          <input id="organisation-list-filter" type="text" class="list-filter-input form-control js-filter-list-input" placeholder="Search organisations">
        </form>
      </li>
    <% end %>
    <%= user_filter_list_items(filter_type) %>
  </ul>
</li>

signonotron2/app/views/users/_user_filter_group_no_js.html.erb
<% if params[filter_type] %>
  <% filter_title = title_from(filter_type) %>
  <div class="if-js-hide row">
    <nav class="filters col-md-8">
      <div class="panel panel-default">
        <header class="panel-heading">
          <ul class='nav nav-pills'>
            <li class="nav-pill-text">
              <strong><%= filter_title %></strong>
            </li>
            <%= user_filter_list_items(filter_type) %>
          </ul>
        </header>
      </div>
    </nav>
  </div>
<% end %>

signonotron2/app/views/users/edit.html.erb
<% content_for :title, "Edit [#{@user.name}]" %>

<h1>Edit &ldquo;<%= @user.name %>&rdquo;</h1>

<p class="suspenders">
  User <strong><%= @user.status %></strong> &bull;
  <%= link_to "Account access log", event_logs_user_path(@user) %> &bull;
  <%= link_to "#{@user.suspended? ? "Uns" : "S"}uspend user", edit_suspension_path(@user) %>
</p>

<% if @user.access_locked? %>
  <div class="alert alert-warning">
    <strong>Account has been locked after too many unsuccessful login attempts.</strong><br/>
    Locked accounts are automatically unlocked after 1 hour.
    <%= form_tag unlock_user_path(@user), class: 'unlock-account-form' do %>
      <%= submit_tag "Unlock account", :class => 'btn btn-default add-top-margin' %>
    <% end %>
  </div>
<% end %>

<% if @user.suspended? and @user.reason_for_suspension.present? %>
  <p class="alert alert-warning">
    <strong>User suspended:</strong> <em><%= @user.reason_for_suspension %></em>
  </p>
<% end %>

<%= form_for @user, :html => {:class => 'well add-top-margin'} do |f| %>

  <%= render partial: "form_errors" %>
  <%= render partial: "form_fields", locals: { f: f } %>

  <hr>

  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

signonotron2/app/views/users/edit_email_or_passphrase.html.erb
<% content_for :title, "Edit your account" %>

<div class="page-title">
  <h1>Edit your account</h1>
</div>

<%= render partial: "form_errors" %>

<section class="well">
  <h2 class="remove-top-margin remove-bottom-margin">Change your email address</h2>
  <p class="text-muted bold">Changing your email address doesn’t take effect until you follow the link in a confirmation email sent to the new address.</p>
  <%= form_for current_user, :url => update_email_user_path do |f| %>
    <% if f.object.unconfirmed_email.present? %>
      <p class="form-group">
        <%= f.label :unconfirmed_email, "You have a pending email change" %>
        <%= f.text_field :unconfirmed_email, readonly: "readonly", disabled: "disabled", class: 'form-control input-md-6' %>
      </p>
      <div class="add-bottom-margin">
        <%= link_to "Resend email change", resend_email_change_user_path(f.object), :method => :put, :class => "btn btn-primary add-right-margin" %>
        <%= link_to "Cancel email change", cancel_email_change_user_path(f.object), :method => :delete, :class => "btn btn-danger" %>
      </div>
      <hr />
    <% end %>
    <p class="form-group">
      <%= f.label(:email, "Email") %>
      <%= f.text_field :email, class: 'form-control input-md-6' %>
    </p>
    <%= f.submit "Change email", class: "btn btn-primary" %>
  <% end %>
</section>
<section class="well">
  <h2 class="remove-top-margin"><%= t(".change_passphrase") %></h2>
  <%= form_for current_user, :url => update_passphrase_user_path do |f| %>
    <%= render partial: "devise/passwords/change_password_panel", locals: { f: f, user: current_user, updating_password: true } %>
  <% end %>
</section>

signonotron2/app/views/users/event_logs.html.erb
<% content_for :title, "Account access log" %>

<ol class="breadcrumb">
  <li><%= link_to @user.name, edit_user_path_by_user_type(@user) %></li>
  <li class="active">Account access log</li>
</ol>

<div class="page-title">
  <h1>Account access log</h1>
  <% if @logs.any? %><h2 class="text-muted remove-top-margin"><%= pluralize(number_with_delimiter(@logs.total_count), 'event') %></h2><% end %>
</div>

<% if @logs.any? %>
  <%= paginate(@logs, theme: 'twitter-bootstrap-3', pagination_class: 'remove-top-margin') %>

  <table class="table table-bordered table-striped">
    <thead>
      <tr class="table-header">
        <th style="width: 200px">Time</th>
        <th>Event</th>
      </tr>
    </thead>
    <tbody>
      <% @logs.each do |log| %>
        <tr>
          <td><%= log.created_at.to_s(:govuk_date_short) %></td>
          <td>
            <%= log.event %>
            <% if log.application %>
              for <strong><%= log.application.name %></strong>
            <% end %>
            <% if log.initiator %>
              by <strong><%= link_to log.initiator.name, users_path(filter: log.initiator.email), title: log.initiator.email %></strong>
            <% end %>
            <%= log.trailing_message %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate(@logs, theme: 'twitter-bootstrap-3', pagination_class: 'remove-top-margin') %>
<% else %>
  <div class="no-content no-content-bordered">
    No activity logged
  </div>
<% end %>

signonotron2/app/views/users/index.html.erb
<% content_for :title, user_role_text %>

<div class="page-title clearfix remove-top-margin">
  <h1 class="pull-left"><%= user_role_text %></h1>
  <div class="pull-right add-top-margin">
    <%= link_to "Create user", new_user_invitation_path, class: "btn btn-success add-right-margin" %>
    <% if policy(User).new? %>
      <%= link_to "Upload a batch of users", new_batch_invitation_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

<%= render partial: "user_filter" %>
<%= render partial: "pagination", locals: {position: 'top'} %>

<table class="table table-striped table-bordered">
  <thead>
    <tr class="table-header">
      <th scope="col">Name and email</th>
      <th scope="col">Role</th>
      <th scope="col">Organisation</th>
      <th scope="col">Sign-in count</th>
      <th scope="col">Last sign-in</th>
      <th scope="col">Created</th>
      <th scope="col">Status</th>
      <th scope="col"><%= two_step_abbr_tag %> Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="email">
          <%= user.suspended? ? "<del>".html_safe : "" %>
            <strong>
              <%= link_to "#{user.name}", edit_user_path(user) %>
            </strong>
          <%= user.suspended? ? "</del>".html_safe : "" %>
          <br><span class="text-muted"><%= user.email %></span>
        </td>
        <td class="role"><%= user.role.humanize %></td>
        <td class="organisation"><%= user.organisation.try(:name) %></td>
        <td><%= user.sign_in_count %></td>
        <td class="last-sign-in">
          <% if user.current_sign_in_at %>
            <%= time_ago_in_words(user.current_sign_in_at) %> ago
          <% else %>
            never signed in
          <% end %>
        </td>
        <td><%= time_ago_in_words(user.created_at) %> ago</td>
        <td><%= user.status.humanize %></td>
        <td><%= two_step_status(user) %></td>
        <td>
          <% if user.invited_but_not_accepted %>
            <%= form_tag resend_user_invitation_path(user) do %>
              <%= submit_tag "Resend signup email", :class => 'btn btn-sm btn-default' %>
            <% end %>
          <% end %>
          <% if user.access_locked? %>
            <%= form_tag unlock_user_path(user) do %>
              <%= submit_tag "Unlock account", :class => 'btn btn-default' %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render partial: "pagination" %>

signonotron2/app/views/users/two_step_flagged.html.erb
<p>Hello <%= @user.name %>,</p>

<p>Make your Signon account more secure by setting up 2-step verification.</p>

<p>You’ll be asked to set this up next time you sign in. You’ll need to install
an app on your phone which will generate a verification code to enter when you
sign in.</p>

<p><%= link_to 'GOV.UK', "https://www.gov.uk" %> team</p>
<p>Government Digital Service</p>